# gen-setup-version.ps1 — 为安装包生成版本资源（AssemblyInfo），版本取自 Cargo.toml
#
# 为什么需要它：安装包 DSHLauncherSetup.exe 之前没有任何 AssemblyVersion /
# AssemblyFileVersion 特性，资源管理器里显示 `FileVersion 0.0.0.0`、产品名为空
# ——与启动器 exe 的版本资源、注册表 DisplayVersion 三者不一致。
#
# 只把版本号**注入**安装包，不新增手写版本来源：唯一来源仍是
# Cargo.toml 的 [workspace.package] version（与 DSHLauncherSetup.cs 的
# AppVersion 由 tools/verify-version.ps1 强制校验一致）。
#
# 用法: pwsh -NoProfile -File tools\gen-setup-version.ps1 -Out <生成的 .cs 路径>
#       退出码 0 = 正常；1 = 无法确定版本

param(
    [Parameter(Mandatory = $true)]
    [string]$Out
)

# Windows PowerShell 5.1 的 Get-Content 默认按 **ANSI 代码页**（本机 gb2312）解码，
# 会把本仓库的 UTF-8 源码/文档读成乱码 -> 全部中文断言假失败。这条全局默认参数在 PS 5.1/7 都有效。
$PSDefaultParameterValues['Get-Content:Encoding'] = 'UTF8'

$ErrorActionPreference = 'Stop'
$here = Split-Path -Parent $MyInvocation.MyCommand.Path
$root = Split-Path -Parent $here

# ---- 1. 读取唯一版本来源 ----
$cargoToml = Get-Content (Join-Path $root 'Cargo.toml') -Raw
$m = [regex]::Match($cargoToml, '(?ms)^\[workspace\.package\].*?^\s*version\s*=\s*"([^"]+)"')
if (-not $m.Success) {
    Write-Error 'Cargo.toml 的 [workspace.package] 未声明 version'
    exit 1
}
$version = $m.Groups[1].Value

# ---- 2. 解析为四段式 AssemblyVersion ----
$core = ($version -split '[-+]')[0]
$seg = @($core.Split('.'))
while ($seg.Count -lt 4) { $seg += '0' }
$numeric = ($seg[0..3] -join '.')

# ---- 3. 生成 AssemblyInfo（C# 5 兼容：仅特性，不用新语法） ----
# 文件以纯 ASCII 写出（避免编码/BOM 干扰 Win32 版本资源生成）：
#   - 注释用英文，避免中文在 ascii 编码下变成 "?"；
#   - 版权符号写 (C)，不用 \u00A9（C# 字符串没有反斜杠 u 转义）；
#   - C# 属性里的引号用 PowerShell 反引号转义 `` `" `` 书写
#     （PowerShell 双引号字符串中 `\"` 不是转义，反斜杠是字面量）。
$copyright = 'Copyright (C) 2026 KristoffersonLee'
$lines = @(
    '// AUTO-GENERATED by tools/gen-setup-version.ps1 - DO NOT EDIT.',
    '// Single source of truth for the version: Cargo.toml [workspace.package] version.',
    'using System.Reflection;',
    '',
    '[assembly: AssemblyTitle("DeepSeek Harness Launcher Setup")]',
    '[assembly: AssemblyProduct("DeepSeek Harness Launcher")]',
    '[assembly: AssemblyCompany("KristoffersonLee")]',
    "[assembly: AssemblyCopyright(`"$copyright`")]",
    "[assembly: AssemblyVersion(`"$numeric`")]",
    "[assembly: AssemblyFileVersion(`"$numeric`")]",
    "[assembly: AssemblyDescription(`"DeepSeek Harness Launcher $version installer`")]"
)

$dir = Split-Path -Parent $Out
if ($dir -and -not (Test-Path $dir)) { New-Item -ItemType Directory -Path $dir -Force | Out-Null }
# ASCII + CRLF：Win32 版本资源由 csc 从这些特性生成，编码无关紧要，但保持文件干净
Set-Content -Path $Out -Value ($lines -join "`r`n") -Encoding ascii
Write-Host "已生成版本资源: $Out (AssemblyVersion=$numeric, ProductVersion=$version)" -ForegroundColor DarkGray
exit 0
